=== Liming-Zheng/paparazzi/conf/gcs/layout.dtd
<!ELEMENT layout (rows|columns|widget)>
<!ELEMENT rows (columns|widget)*>
<!ELEMENT columns (rows|widget)*>
<!ELEMENT widget (papget)*>
<!ELEMENT papget EMPTY>

<!ATTLIST layout
width CDATA #IMPLIED
height CDATA #IMPLIED
>

<!ATTLIST rows
size CDATA #IMPLIED
>

<!ATTLIST columns
size CDATA #IMPLIED
>

<!ATTLIST widget
name CDATA #REQUIRED
size CDATA #IMPLIED
>

<!ATTLIST papget
field CDATA #REQUIRED
x CDATA #REQUIRED
y CDATA #REQUIRED
format CDATA #IMPLIED
>

=== Liming-Zheng/paparazzi/conf/gcs/tmp_papgets.xml
<!DOCTYPE layout SYSTEM "layout.dtd">

<layout width="1024" height="768">
 <rows>
  <widget size="500" name="map2d">
    <papget field="ESTIMATOR:z" x="10" y="150" format="Alt:%.0fm"/>
    <papget field="ESTIMATOR:z_dot" x="10" y="200" format="Climb:%.1fm/s"/>
  </widget>
  <columns>
   <rows size="375">
    <widget size="200" name="strips"/>
   </rows>
   <widget size="400" name="aircraft"/>
   <widget name="alarms"/>
  </columns>
 </rows>
</layout>
