=== Liming-Zheng/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (waypoints,include*,exceptions?,blocks)>


<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|circle|deroute|stay|follow|survey_rectangle)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (while|heading|attitude|go|xyz|set|circle|deroute|stay)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>

<!ATTLIST flight_plan name CDATA #REQUIRED>
<!ATTLIST flight_plan lat0 CDATA #REQUIRED>
<!ATTLIST flight_plan lon0 CDATA #REQUIRED>
<!ATTLIST flight_plan max_dist_from_home CDATA #REQUIRED>
<!ATTLIST flight_plan qfu CDATA #REQUIRED>
<!ATTLIST flight_plan ground_alt CDATA #REQUIRED>
<!ATTLIST flight_plan security_height CDATA #REQUIRED>
<!ATTLIST flight_plan alt CDATA #REQUIRED>
<!ATTLIST flight_plan ir_square_utmx_min CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_utmy_max CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_width CDATA #IMPLIED>
<!ATTLIST flight_plan ir_correct_steps CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #REQUIRED
y CDATA #REQUIRED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED>

<!ATTLIST block 
name CDATA #REQUIRED
strip_button CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST heading 
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST go 
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
approaching_time CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED
until CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED>

<!ATTLIST xyz
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
radius CDATA #IMPLIED>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
gaz CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED>


<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
gaz CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
rotate CDATA #IMPLIED>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

=== Liming-Zheng/paparazzi/conf/flight_plans/tudelft/rotating_wing25kg_HARDE.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="120" ground_alt="60" lat0="52.3931434" lon0="5.9205099" max_dist_from_home="9000" name="Rotating wing Harde" security_height="2">
  <header/>
  <waypoints>
    <waypoint name="HOME" x="12.6" y="-48.7"/>
    <waypoint name="CLIMB" x="62.6" y="-80.4"/>
    <waypoint name="trans" x="100." y="100."/>
    <waypoint name="decel" x="100." y="100."/>
    <waypoint name="end_trans" x="100." y="100."/>
    <waypoint name="STDBY" lat="52.3940343" lon="5.9229692"/>
    <waypoint name="begin_trans"  lat="52.3941568" lon="5.9231750"/>
    <waypoint name="p1" lat="52.3963465" lon="5.9267684"/>
    <waypoint name="p2" lat="52.3994182" lon="5.9333586"/>
    <waypoint name="p3" lat="52.4033999" lon="5.9292886"/>
    <waypoint name="p4" lat="52.3999490" lon="5.9231485"/>
    <waypoint name="circ" lat="52.39535877874752" lon="5.924914921610622"/>
    <waypoint name="TD" lat="52.39306725044085" lon="5.92060993591204"/>
    <waypoint lat="52.4034734" lon="5.9067552" name="C1"/>
    <waypoint lat="52.3878517" lon="5.9212118" name="C2"/>
    <waypoint lat="52.4054122" lon="5.9581765" name="C3"/>
    <waypoint lat="52.4179727" lon="6.0083051" name="C4"/>
    <waypoint lat="52.442091206182084" lon="5.987117813607398" name="C5"/>
  </waypoints>
  <sectors>
    <sector color="red" name="Flyzone">
      <corner name="C1"/>
      <corner name="C2"/>
      <corner name="C3"/>
      <corner name="C4"/>
      <corner name="C5"/>
    </sector>
  </sectors>
  <modules>
    <!--<module name="follow_me"/>-->
  </modules>
  <exceptions>
    <exception cond="Or(!InsideFlyzone(GetPosX(), GetPosY()), GetPosAlt() @GT GetAltRef() + 1500) @AND !(nav_block == IndexOfBlock('Wait GPS')) @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point'))" deroute="Holding point"/>
    <exception cond="datalink_time @GT 25 @AND !(nav_block == IndexOfBlock('Wait GPS')) @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point')) @AND !(nav_block == IndexOfBlock('Standby'))" deroute="Standby"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <set value="false" var="force_forward"/>
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid() || !state.ned_initialized_i"/>
    </block>
    <block name="Geo init">
      <set value="false" var="force_forward"/>
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="false" var="force_forward"/>
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine">
        <set value="false" var="force_forward"/>
        <call_once fun="NavResurrect()"/>
        <attitude pitch="0" roll="0" throttle="0" until="stage_time>10" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
        <set value="false" var="force_forward"/>
        <exception cond="getPosAlt() @LT 4.0" deroute="Standby"/>
        <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
        <attitude pitch="0" roll="0" throttle="0.75" until="stage_time>2" vmode="throttle"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
        <set value="false" var="force_forward"/>
        <stay wp="STDBY"/>
    </block>
    <block name="stay_p1">
      <set value="false" var="force_forward"/>
      <stay wp="p1"/>
    </block>
    <block name="go_p2">
      <set value="false" var="force_forward"/>
      <call_once fun="nav_set_heading_deg(90)"/>
      <go wp="p2"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="line_p1_p2">
      <set value="false" var="force_forward"/>
      <go from="p1" hmode="route" wp="p2"/>
      <stay wp="p2"/>
    </block>
    <block name="line_trans_fwd">
      <set value="false" var="force_forward"/>
      <call_once fun="NavSetWaypointHere(WP_p1)"/>
      <stay wp="end_trans"/>
    </block>
    <block name="line_trans_quad">
      <set value="false" var="force_forward"/>
      <call_once fun="NavSetWaypointHere(WP_p1)"/>
      <stay wp="end_trans"/>
    </block>
    <block name="route">
      <set value="false" var="force_forward"/>
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      <deroute block="route"/>
    </block>
    <block name="Oval">
      <set value="false" var="force_forward"/>
      <oval p1="p1" p2="p2" radius="100"/>
    </block>
    <block name="Circle_CW">
      <set value="false" var="force_forward"/>
      <circle radius="100" wp="circ"/>
    </block>
    <block name="Circle_CCW">
      <set value="false" var="force_forward"/>
      <circle radius="-100" wp="circ"/>
    </block>
    <block name="Circle_CW_fwd">
      <set value="true" var="force_forward"/>
      <circle radius="100" wp="circ"/>
    </block>
    <block name="Circle_CCW_fwd">
      <set value="true" var="force_forward"/>
      <circle radius="-100" wp="circ"/>
    </block>
    <block name="land here" strip_button="Land Here" strip_icon="land-right.png">
        <set value="false" var="force_forward"/>
        <call_once fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="land">
        <set value="false" var="force_forward"/>
        <go wp="TD"/>
    </block>
    <block name="descend">
        <set value="false" var="force_forward"/>
        <exception cond="!(getPosAlt() @LT 12.0)" deroute="flare"/>
        <stay climb="-1.0" vmode="climb" wp="TD"/>
    </block>
    <block name="flare">
        <set value="false" var="force_forward"/>
        <stay climb="-0.5" vmode="climb" wp="TD"/>
        <exception cond="!(getPosAlt() @LT 2.0)" deroute="flare_low"/>
    </block>
    <block name="flare_low">
        <set value="false" var="force_forward"/>
        <!-- <exception cond="NavDetectGround()" deroute="Holding point"/> -->
        <exception cond="!nav_is_in_flight()" deroute="landed"/>
        <!-- <call_once fun="NavStartDetectGround()"/> -->
        <!-- <stay climb="-0.5" vmode="climb" wp="TD"/> -->
    </block>
    <block name="landed">
        <set value="false" var="force_forward"/>
        <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== Liming-Zheng/paparazzi/conf/flight_plans/AM/overactuated_vehicle_IMAV_test_corn.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="325" ground_alt="262" lat0="50.7291180" lon0="5.8873630" max_dist_from_home="1000" name="Overactuated vehicle IMAV test corn Belgium" security_height="300">
  <header>
    #include "autopilot.h"
    #include "modules/datalink/datalink.h"
    #include "modules/Overactuated_vehicle/Overactuated_mixing.h"
    static inline bool delay_test_rc(bool test, int delay) {
      static int nb = 0;
        if (test) {
        nb++;
        if (nb == delay) {
          nb = 0;
          return true;
        }
        return false;
      } else {
        nb = 0;
        return false;
      }
    }
</header>
  <waypoints>
    <waypoint name="HOME" x="-9.0" y="10.3"/>
    <waypoint name="CLIMB" x="-43.4" y="29.2"/>
    <waypoint lat="50.729854" lon="5.886833" name="STDBY"/>
    <waypoint lat="50.730109" lon="5.885623" name="p1"/>
    <waypoint lat="50.729854" lon="5.888500" name="p2"/>
    <waypoint lat="50.728612" lon="5.887800" name="p3"/>
    <waypoint lat="50.729062" lon="5.885219" name="p4"/>
    <waypoint lat="50.729280" lon="5.886908" name="TD"/>
    <waypoint lat="50.727389" lon="5.880006" name="APP"/>
    <waypoint lat="50.730339" lon="5.884213" name="FOLLOW"/>
    <waypoint lat="50.729894" lon="5.884254" name="FOLLOW_ARUCO"/>
    <waypoint lat="50.732349" lon="5.896132" name="C1"/>
    <waypoint lat="50.728289" lon="5.898325" name="C2"/>
    <waypoint lat="50.724964" lon="5.895894" name="C3"/>
    <waypoint lat="50.723357" lon="5.888871" name="C4"/>
    <waypoint lat="50.725053" lon="5.881581" name="C5"/>
    <waypoint lat="50.728354" lon="5.877497" name="C6"/>
    <waypoint lat="50.732845" lon="5.878703" name="C7"/>
    <waypoint lat="50.735052" lon="5.888368" name="C8"/>
    <waypoint lat="50.734087" lon="5.893085" name="C9"/>
    <waypoint lat="50.727626" lon="5.894904" name="FLY1"/>
    <waypoint lat="50.726570" lon="5.893148" name="FLY2"/>
    <waypoint lat="50.725408" lon="5.889846" name="FLY3"/>
    <waypoint lat="50.726017" lon="5.886084" name="FLY4"/>
    <waypoint lat="50.727508" lon="5.882457" name="FLY5"/>
    <waypoint lat="50.729849" lon="5.880736" name="FLY6"/>
    <waypoint lat="50.732038" lon="5.883784" name="FLY7"/>
    <waypoint lat="50.732494" lon="5.889264" name="FLY8"/>
    <waypoint lat="50.728871" lon="5.895051" name="FLY9"/>
  </waypoints>
  <sectors>
    <sector color="orange" name="Safe_area">
      <corner name="FLY1"/>
      <corner name="FLY2"/>
      <corner name="FLY3"/>
      <corner name="FLY4"/>
      <corner name="FLY5"/>
      <corner name="FLY6"/>
      <corner name="FLY7"/>
      <corner name="FLY8"/>
      <corner name="FLY9"/>
    </sector>
    <sector color="red" name="Flight_area">
      <corner name="C1"/>
      <corner name="C2"/>
      <corner name="C3"/>
      <corner name="C4"/>
      <corner name="C5"/>
      <corner name="C6"/>
      <corner name="C7"/>
      <corner name="C8"/>
      <corner name="C9"/>
    </sector>
  </sectors>
  <modules>
    <module name="follow_me"/>
  </modules>
  <exceptions>
    <exception cond="(!InsideSafe_area(GetPosX(), GetPosY()) @OR GetPosAlt() @GT GetAltRef() + 110) 
    @AND (nav_block @GT IndexOfBlock('Standby')) @AND (nav_block @LT IndexOfBlock('landed')) @AND !(nav_block == IndexOfBlock('Wait GPS')) 
    @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point'))" deroute="Standby"/>
    <exception cond="(!InsideFlight_area(GetPosX(), GetPosY()) @OR GetPosAlt() @GT GetAltRef() + 120) 
    @AND (nav_block @GT IndexOfBlock('Standby')) @AND (nav_block @LT IndexOfBlock('landed')) @AND !(nav_block == IndexOfBlock('Wait GPS')) 
    @AND !(nav_block == IndexOfBlock('Geo init')) @AND !(nav_block == IndexOfBlock('Holding point'))" deroute="landed"/>
    <exception cond="electrical.bat_low @AND autopilot_in_flight() @AND (nav_block @GT IndexOfBlock('Standby')) 
                     @AND (nav_block @LT IndexOfBlock('landed'))" deroute="descend"/>
    <exception cond="(nav_block @GT IndexOfBlock('Standby') @AND nav_block @LT IndexOfBlock('landed'))
    @AND GpsIsLost() @AND delay_test_rc(RadioControlIsLost(),20)" deroute="landed"/>
    <exception cond="(GpsIsLost() @AND (datalink_time @GT 15) @AND nav_block @GT IndexOfBlock('Standby') 
                     @AND nav_block @LT IndexOfBlock('landed'))" deroute="Enter_AP_MODE_RC_DIRECT"/>
  </exceptions>
  <blocks>
    <block name="Enter_AP_MODE_RC_DIRECT">
      <set value="AP_MODE_RC_DIRECT" var="autopilot.mode"/>
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
    </block>
    <block name="Wait GPS">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid() || !state.ned_initialized_i"/>
    </block>
    <block name="Geo init">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" pre_call="NavKillThrottle()" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine">
      <set value="1" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <call_once fun="NavResurrect()"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <stay climb="-0.5" vmode="climb" wp="TD"/>
    </block>
    <block name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <set value="1" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <exception cond="stateGetPositionEnu_f()->z > 10.0" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="STDBY"/>
    </block>
    <block name="Follow_Aruco">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="FOLLOW_ARUCO"/>
    </block>
    <block name="follow_module">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <stay pre_call="follow_me_set_wp(WP_FOLLOW, 0)" wp="FOLLOW"/>
    </block>
    <block name="stay_p1">
      <set value="0" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <stay wp="p1"/>
    </block>
    <block name="go_p2">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <call_once fun="nav_set_heading_deg(90)"/>
      <go wp="p2"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="line_p1_p2">
      <set value="0" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <stay until="stage_time>10" wp="p1"/>
      <go from="p1" hmode="route" wp="p2"/>
      <stay wp="p2"/>
    </block>
    <block name="wp_goto_route">
      <set value="1" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <go wp="p1"/>
      <go wp="p2"/>
      <go wp="p3"/>
      <go wp="p4"/>
      <deroute block="wp_goto_route"/>
    </block>
    <block name="route">
      <set value="1" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      <deroute block="route"/>
    </block>
    <block name="Oval">
      <set value="1" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <oval p1="p1" p2="p2" radius="100"/>
    </block>
    <block name="Circle_CW">
      <set value="1" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <circle radius="100" wp="p1"/>
    </block>
    <block name="Circle_CCW">
      <set value="1" var="force_forward"/>
      <set value="0" var="approach_state"/>
      <circle radius="-100" wp="p1"/>
    </block>
    <block name="Approach APP">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <stay alt="WaypointAlt(WP_APP)" pre_call="approach_moving_target_enable(WP_APP)" wp="APP"/>
    </block>
    <block name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <set value="1" var="approach_state"/>
      <set value="0" var="force_forward"/>
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="land">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <go wp="TD"/>
    </block>
    <block name="descend">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <exception cond="!(stateGetPositionEnu_f()->z > 12.0)" deroute="flare"/>
      <stay climb="-1.5" vmode="climb" wp="TD"/>
    </block>
    <block name="flare">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <stay climb="-0.8" vmode="climb" wp="TD"/>
      <exception cond="!(stateGetPositionEnu_f()->z > 1.0)" deroute="flare_low"/>
      <exception cond="agl_dist_valid @AND !(agl_dist_value > 0.50)" deroute="flare_low"/>
    </block>
    <block name="flare_low">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <exception cond="detect_ground_on_landing()" deroute="landed"/>
      <stay climb="-0.5" vmode="climb" wp="TD"/>
    </block>
    <block name="landed">
      <set value="0" var="force_forward"/>
      <set value="1" var="approach_state"/>
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== Liming-Zheng/paparazzi/conf/flight_plans/basic.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan alt="75" ground_alt="0" lat0="43.4622" lon0="1.2729" max_dist_from_home="1500" name="Basic" qfu="270" security_height="25">
  <header>
#include "nav_line.h"
#include "datalink.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="STDBY" x="20" y="80"/>
    <waypoint name="1" x="44.8" y="102.2"/>
    <waypoint name="2" x="-63.5" y="122.9"/>
    <waypoint name="MOB" x="-11.5" y="-21.2"/>
    <waypoint name="S1" x="-151.6" y="80.4"/>
    <waypoint name="S2" x="180.1" y="214.9"/>
    <waypoint alt="30" name="AF" x="200" y="-10"/>
    <waypoint name="TOD" x="8.0" y="-22.7"/>
    <waypoint alt="0" name="TD" x="80.0" y="20.0"/>
    <waypoint name="BASELEG" x="26.9" y="-23.0"/>
    <waypoint name="CLIMB" x="-122.5" y="35.4"/>
  </waypoints>
  <exceptions>
    <exception cond="datalink_time > 22" deroute="Standby"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <set value="1" var="kill_throttle"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="1" var="kill_throttle"/>
      <attitude roll="0" throttle="0" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_icon="takeoff.png" strip_button="Takeoff (wp CLIMB)">
      <exception cond="estimator_z > ground_alt+25" deroute="Standby"/>
      <set value="0" var="kill_throttle"/>
      <set value="0" var="estimator_flight_time"/>
      <go wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block name="Figure 8 around wp 1" strip_button="Figure 8 (wp 1-2)" strip_icon="eight.png">
      <eight center="1" radius="nav_radius" turn_around="2"/>
    </block>
    <block name="Oval 1-2" strip_button="Oval (wp 1-2)" strip_icon="oval.png">
      <oval p1="1" p2="2" radius="nav_radius"/>
    </block>
    <block name="MOB" strip_button="Turn around here" strip_icon="mob.png">
      <call fun="NavSetWaypointHere(WP_MOB)"/>
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <circle radius="nav_radius" wp="MOB"/>
    </block>
    <block name="Line 1-2" strip_button="Line (wp 1-2)" strip_icon="line.png">
      <call fun="nav_line_init()"/>
      <call fun="nav_line(WP_1, WP_2, nav_radius)"/>
    </block>
    <block name="Survey S1-S2" strip_button="Survey (wp S1-S2)" strip_icon="survey.png">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>
    <block name="Land Right AF-TD" strip_button="Land right (wp AF-TD)" strip_icon="land-right.png">
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="Land Left AF-TD" strip_button="Land left (wp AF-TD)" strip_icon="land-left.png">
      <set value="-DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="land">
      <call fun="nav_compute_baseleg(WP_AF, WP_TD, WP_BASELEG, nav_radius)"/>
      <circle radius="nav_radius" until="NavCircleCount() > 0.5" wp="BASELEG"/>
      <set value="V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE" var="v_ctl_auto_throttle_cruise_throttle"/>
      <circle radius="nav_radius" until="NavQdrCloseTo(DegOfRad(baseleg_out_qdr)-10) && 10 > fabs(estimator_z - WaypointAlt(WP_BASELEG))" wp="BASELEG"/>
    </block>
    <block name="final">
      <exception cond="ground_alt + 10 > estimator_z" deroute="flare"/>
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>
    <block name="flare">
      <go approaching_time="0" from="TOD" hmode="route" throttle="0.0" vmode="throttle" wp="TD"/>
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== Liming-Zheng/paparazzi/conf/flight_plans/IS.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan ground_alt="200" alt="250" lat0="43.4624" lon0="1.2727" max_dist_from_home="1500" name="Intelligent Surveillance" qfu="270" security_height="25">
<header>
#include "anemotaxis.h"
#include "chemotaxis.h"
#include "discsurvey.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="1" x="200" y="0"/>
    <waypoint name="2" x="0" y="200"/>
    <waypoint name="MOB" x="200" y="200"/>
    <waypoint name="S1" x="-200" y="-200"/>
    <waypoint name="S2" x="300" y="400"/>
    <waypoint name="C" x="-250" y="-200"/>
    <waypoint name="C1" x="-200" y="-200"/>
    <waypoint name="C2" x="300" y="400"/>
    <waypoint name="PLUME" x="400" y="400"/>
  </waypoints>
  <blocks>
<!--
    <block name="wait GPS">
      <while cond="!GpsFixValid()"/>
    </block>

    <block name="init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
      <deroute block="circle 1"/>
    </block>
-->

    <block name="circle 1">
      <circle radius="75" wp="1"/>
    </block>

    <block name="eight 1">
      <eight radius="75" center="1" turn_around="2"/>
    </block>

    <block name="oval" strip_button="Oval">
      <oval p1="1" p2="2" radius="80"/>
    </block>

    <block name="MOB" strip_button="MOB">
      <call fun="NavSetWaypointHere(WP_MOB)"/>
      <circle wp="MOB" radius="100"/>
    </block>

    <block name="Anemotaxis" strip_button="Anemotaxis">
      <call fun="nav_anemotaxis_downwind(WP_C)"/>
      <go wp="C" hmode="route" approaching_time="0"/>
      <call fun="nav_anemotaxis_init(WP_C)"/>
      <call fun="nav_anemotaxis(WP_C, WP_C1, WP_C2, WP_PLUME)"/>
    </block>

    <block name="Chemotaxis" strip_button="Chemotaxis">
      <call fun="nav_chemotaxis_init()"/>
      <call fun="nav_chemotaxis(WP_C, WP_PLUME)"/>
    </block>

    <block name="Disc survey" strip_button="DS">
      <call fun="disc_survey_init()"/>
      <call fun="disc_survey(WP_HOME, 500)"/>
    </block>

    <block name="circle 1 auto pitch">
      <circle radius="75" wp="1" pitch="auto" throttle="0.7"/>
    </block>

    <block name="circle left 1">
      <circle radius="-75" wp="1"/>
    </block>

    <block name="climb 75">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.75" pitch="0.3" vmode="throttle" until="10 > PowerVoltage()"/>
    </block>

    <block name="climb 1">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" climb="1" pitch="0.1" vmode="climb" until="10 > PowerVoltage()"/>
    </block>

    <block name="descent 0" strip_button="Descent">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.0" pitch="-0.3" vmode="throttle" until="ground_alt+50 > estimator_z"/>
      <deroute block="circle 1"/>
    </block>

    <block name="route12">
      <go approaching_time="0" from="1" hmode="route" wp="2"/>
    </block>

    <block name="glide12">
      <go from="1" hmode="route" vmode="glide" wp="2"/>
    </block>

    <block name="stack 2">
      <circle radius="75" wp="2"/>
    </block>

    <block name="route21">
      <go approaching_time="0" from="2" hmode="route" wp="1"/>
    </block>

    <block name="stack 1">
      <circle radius="75" wp="1"/>
    </block>

    <block name="survey">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>

    <block name="follow">
      <follow ac_id="5" distance="25" height="10"/>
    </block>
  </blocks>
</flight_plan>
