=== Liming-Zheng/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (waypoints,include*,exceptions?,blocks)>


<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|go|xyz|set|circle|deroute|stay|follow|survey_rectangle)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (while|heading|attitude|go|xyz|set|circle|deroute|stay)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>

<!ATTLIST flight_plan name CDATA #REQUIRED>
<!ATTLIST flight_plan lat0 CDATA #REQUIRED>
<!ATTLIST flight_plan lon0 CDATA #REQUIRED>
<!ATTLIST flight_plan max_dist_from_home CDATA #REQUIRED>
<!ATTLIST flight_plan qfu CDATA #REQUIRED>
<!ATTLIST flight_plan ground_alt CDATA #REQUIRED>
<!ATTLIST flight_plan security_height CDATA #REQUIRED>
<!ATTLIST flight_plan alt CDATA #REQUIRED>
<!ATTLIST flight_plan ir_square_utmx_min CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_utmy_max CDATA #IMPLIED>
<!ATTLIST flight_plan ir_square_width CDATA #IMPLIED>
<!ATTLIST flight_plan ir_correct_steps CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #REQUIRED
y CDATA #REQUIRED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED>

<!ATTLIST block 
name CDATA #REQUIRED
strip_button CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST heading 
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST go 
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
approaching_time CDATA #IMPLIED
gaz CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED
until CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED>

<!ATTLIST xyz
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
cam_ac_target CDATA #IMPLIED
target CDATA #IMPLIED
radius CDATA #IMPLIED>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
cam_mode (null|fix|manual|nadir|target|follow) #IMPLIED
target CDATA #IMPLIED
cam_ac_target CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
gaz CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED>


<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
gaz CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
rotate CDATA #IMPLIED>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

=== Liming-Zheng/paparazzi/conf/flight_plans/versatile.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan ground_alt="200" alt="250" lat0="43.46223" lon0="1.27289" max_dist_from_home="1000" name="Versatile" qfu="270" security_height="25">
<header>
#include "bomb.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="1" x="200" y="0"/>
    <waypoint name="2" x="0" y="200"/>
    <waypoint name="MOB" x="200" y="200"/>
    <waypoint name="S1" x="-200" y="-200"/>
    <waypoint name="S2" x="300" y="400"/>
    <waypoint name="AF" x="200" y="-10" alt="215"/>
    <waypoint name="TOD" x="-150" y="0"/>
    <waypoint name="OVERRUN" x="50" y="0"/>
    <waypoint name="TD" x="80" y="20" alt="185"/>
    <waypoint name="BASELEG" x="400" y="300"/>
    <waypoint name="RELEASE" x="400" y="300"/>
    <waypoint name="TARGET" x="300" y="300"/>
    <waypoint name="START" x="300" y="300"/>
    <waypoint name="CLIMB" x="300" y="300"/>
  </waypoints>
  <blocks>
    <block name="wait GPS">
      <while cond="!GpsFixValid()"/>
    </block>

    <block name="init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
      <deroute block="circle 1"/>
    </block>

    <block name="circle 1">
      <circle radius="75" wp="1"/>
    </block>

    <block name="eight 1">
      <eight radius="75" center="1" turn_around="2"/>
    </block>

    <block name="oval" strip_button="Oval">
      <oval p1="1" p2="2" radius="80"/>
    </block>

    <block name="MOB" strip_button="MOB">
      <call fun="NavSetWaypointHere(WP_MOB)"/>
      <circle wp="MOB" radius="100"/>
    </block>

    <block name="circle 1 auto pitch">
      <circle radius="75" wp="1" pitch="auto" throttle="0.7"/>
    </block>

    <block name="circle left 1">
      <circle radius="-75" wp="1"/>
    </block>

    <block name="climb 75">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.75" pitch="0.3" vmode="throttle" until="10 > PowerVoltage()"/>
    </block>

    <block name="climb 1">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" climb="1" pitch="0.1" vmode="climb" until="10 > PowerVoltage()"/>
    </block>

    <block name="descent 0" strip_button="Descent">
      <circle radius="50+(estimator_z-ground_alt)/2" wp="1" throttle="0.0" pitch="-0.3" vmode="throttle" until="ground_alt+50 > estimator_z"/>
      <deroute block="circle 1"/>
    </block>

    <block name="route12">
      <go approaching_time="0" from="1" hmode="route" wp="2"/>
    </block>

    <block name="glide12">
      <go from="1" hmode="route" vmode="glide" wp="2"/>
    </block>

    <block name="stack 2">
      <circle radius="75" wp="2"/>
    </block>

    <block name="route21">
      <go approaching_time="0" from="2" hmode="route" wp="1"/>
    </block>

    <block name="stack 1">
      <circle radius="75" wp="1"/>
    </block>

    <block name="survey">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>

   <block name="land">
      <set value="compute_baseleg()" var="unit"/>
      <circle radius="BOMB_RADIUS" until="NavCircleCount() > 0.5" wp="BASELEG"/>
      <set value="V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE" var="v_ctl_auto_throttle_cruise_throttle"/>
      <circle radius="BOMB_RADIUS" until="NavQdrCloseTo(DegOfRad(bomb_start_qdr)-10) && baseleg_alt_tolerance > fabs(estimator_z - baseleg_alt)" wp="BASELEG"/>
    </block>

    <block name="final">
      <exception cond="ground_alt + 10 > estimator_z" deroute="flare"/>
<!--
      <go alt="baseleg_alt" approaching_time="16" from="AF" hmode="route" wp="TD"/>
      <go approaching_time="2" from="AF" hmode="route" throttle="0.1" vmode="throttle" wp="TD"/>
-->
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>

    <block name="flare">
      <go approaching_time="0" from="AF" hmode="route" throttle="0.0" vmode="throttle" wp="TD"/>
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle"/>
    </block>

    <block name="follow">
      <follow ac_id="7" distance="25" height="10"/>
    </block>

    <block name="step_roll_10">
      <while cond="TRUE">
	<attitude roll="10.0" until=" stage_time > 4" vmode="alt" alt="250"/>
	<attitude roll="-10.0" until="stage_time > 4" vmode="alt" alt="250"/>
      </while>
    </block>

    <block name="step_roll_20">
      <while cond="TRUE">
	<attitude roll="20.0" until=" stage_time > 4" vmode="alt" alt="250"/>
	<attitude roll="-20.0" until="stage_time > 4" vmode="alt" alt="250"/>
      </while>
    </block>

  </blocks>
</flight_plan>

=== Liming-Zheng/paparazzi/conf/flight_plans/slayer_training.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan alt="75" ground_alt="0" lat0="43.4622" lon0="1.2729" max_dist_from_home="800" name="Versatile" qfu="270" security_height="25">
  <header>
#include "datalink.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="E1" x="65.8" y="123.3"/>
    <waypoint name="E2" x="190.1" y="105.6"/>
    <waypoint name="S1" x="-182.7" y="126.0"/>
    <waypoint name="S2" x="307.6" y="257.0"/>
    <waypoint alt="215" name="AF" x="200" y="-10"/>
    <waypoint name="TOD" x="-150" y="0"/>
    <waypoint alt="185" name="TD" x="80" y="20"/>
    <waypoint name="BASELEG" x="309.9" y="138.1"/>
  </waypoints>
  <blocks>
    <block name="wait GPS">
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
      <deroute block="climb"/>
    </block>
    <block name="eight 1">
      <eight center="E1" radius="nav_radius" turn_around="E2"/>
    </block>
    <block name="survey">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>
    <block name="land">
      <call fun="nav_compute_baseleg(WP_AF, WP_TD, WP_BASELEG)"/>
      <circle radius="nav_radius" until="NavCircleCount() > 0.5" wp="BASELEG"/>
      <set value="V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE" var="v_ctl_auto_throttle_cruise_throttle"/>
      <circle radius="nav_radius" until="NavQdrCloseTo(DegOfRad(baseleg_out_qdr)-10) && 10 > fabs(estimator_z - WaypointAlt(WP_BASELEG))" wp="BASELEG"/>
    </block>
    <block name="final">
      <exception cond="ground_alt + 10 > estimator_z" deroute="flare"/>
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>
    <block name="flare">
      <go approaching_time="0" from="AF" hmode="route" throttle="0.0" vmode="throttle" wp="TD"/>
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>
